# TODO: Make PR test build before merging, and trigger production build/deploy after merge
#  Dependabot push events using GITHUB_TOKEN *won't* trigger the build
#  See https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872

name: Dependabot auto-merge
on:
  workflow_dispatch:
  # pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
