name: Build Lompe documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  Build:
    name: Build documentation and deploy to GitHub Pages
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install environment + Lompe
        run: |
          pip install -r requirements.txt
          pip install --editable lompe[extras]
      - name: Sphinx build
        run: make -C docs html
